### ISSUE TITLE
Failure in NextCloud 28: selection of languages impossible

### ISSUE THREAD

**Issue by SergioArbarviro** [nextcloud/integration_deepl#19]
When I attempt to use the  DeepL extension to translate a text, I do see the form with the 2 windows (left: text to be translated - right: empty, ready to receive the translated tex) and the 2 menus (left: original language - right: language in which to translate).

However, when selecting a text in a simple "text" (= .md format):

- there is no possibility to choose the **original** language: the "detect language" option is selected, and cannot be changed;
- there is no possibility to choose the **destination** language: when clicking on the button, the menu displays for a split second, then disappears again, so that there is no chance to select any language.

I have, as you recommend, included the DeepL API key in the relevant "Connected accounts" form.

**Comment by kyteinsky** [comment]
Hello, the drop down issue was fixed some time ago. Can you try again and see if it works now?
Please include the server logs if you see any errors.

**Comment by Painkiller8818** [comment]
Hi, i just installed the deepl integration (1.3.1) on my nextcloud HUB 10 (31.0.5) and i have the same issue.

Is the issue not solved or is it happening again with the new version of nextcloud or deepl integration.

There are simply no languages to select to translate into, no languages show up in the dropdown menu.

Thanks

**Comment by janepie** [comment]
@Painkiller8818 where do you use the translator, from a text file? Can you check if you have the same problem if you open it via the Assistant button in the top bar?

**Comment by janepie** [comment]
Also, did you select an origin language, for example "Detect language"? This has to be set for destination language options to appear (and in text it's not pre-selected)

**Comment by janepie** [comment]
Let's keep this conversation in https://github.com/nextcloud/integration_deepl/issues/34 for now :)
